name: bromelia_cli
description: A sample command-line application with basic argument parsing.
version: 1.0.0
repository: https://github.com/Bromelia-Studio/bromelia_flutter_cli

environment:
  sdk: ^3.9.0

dependencies:
  args: ^2.7.0
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3

executables:
  bromelia_cli: bromelia_cli

assets:
   - templates/flutter_app/
