name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  go_router: ^16.2.4
  theme_tailor_annotation: ^3.1.1
  responsive_builder: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.8.0
  flutter_lints: ^6.0.0
  theme_tailor: ^3.1.1
  intl_utils: ^2.8.12


flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  arb_dir: lib/core/localization
  output_dir: lib/core/localization/generated



