name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  go_router: ^16.2.4
  theme_tailor_annotation: ^3.1.1
  json_annotation: ^4.9.0
  bloc: ^9.0.1
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.8.0
  flutter_lints: ^6.0.0
  theme_tailor: ^3.1.1
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
