##### Intl Utils #####

# Generate localization files using intl_utils
intl-generate:
	dart run intl_utils:generate

##### Build Runner #####

# Generate code
build-runner:
	dart run build_runner build --delete-conflicting-outputs

# Watch for changes and regenerate code automatically
build-runner-watch:
	dart run build_runner watch --delete-conflicting-outputs
